name: statping-ng
version: "stable"
version-script: cat version.txt
summary: Statping-ng Server Monitoring with Status Page
description: |
  An easy to use Status Page for your websites and applications.
  Statping will automatically fetch the application and render a beautiful
  status page with tons of features for you to build an even better status page.
  This Status Page generator allows you to use MySQL, Postgres, or SQLite
  on multiple operating systems.

base: core18
build-base: core18
type: app
confinement: strict
grade: stable
license: GPL-3.0

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  statping:
    command: bin/statping
    daemon: simple
    plugs:
      - home
      - network
      - network-bind

parts:
  statping:
    source: .
    plugin: nil
    override-build: |
      curl -o- -L https://raw.githubusercontent.com/handelsblattgroup/statping/dev/install.sh | bash
    build-packages:
      - tar
      - curl
      - bash
    organize:
      /usr/local/bin/statping: bin/
